DIR_LAB               = lab
NAME                  = course-spring-brasb-build-a-rest-api
IMAGE_SOURCE          = https://github.com/spring-academy/course-spring-brasb-build-a-rest-api
CONTAINER_REGISTRY    = 
CONTAINER_REPOSITORY  = course-spring-brasb-build-a-rest-api
CODE_REPO             = https://github.com/spring-academy/course-spring-brasb-build-a-rest-api-code
CODE_REPO_BRANCH      = main
version               = latest

env                   = local