apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: spr-brasb-first-rest-endpoint
spec:
  title: Develop Your Family Cash Card REST Service
  description: |
    Add the GET endpoint to your Spring project and start testing your Spring data.
  workshop:
    image: jdk17-environment:*
    packages:
      - name: spring-academy-lab
        files:
          - image:
              url:
                ghcr.io/spring-academy/spring-academy-extension-packages/spring-academy-lab
              tagSelection:
                semver:
                  constraints: ">=1.0.0 <2.0.0"
    files:
      - image: # Note: format is {REPOSITORY_NAME}-files
          url: $(image_repository)/course-spring-brasb-build-a-rest-api-files:$(workshop_version)
        includePaths:
          - /workshops/05-first-rest-endpoint/workshop/**
          - /workshops/05-first-rest-endpoint/exercises/**
          - /workshops/05-first-rest-endpoint/README.md
        newRootPath: workshops/05-first-rest-endpoint
      - path: .local/share/code-server
        image:
          url: ghcr.io/spring-academy/vscode-java-tools-$(platform_arch)-files:0.25.14
      - path: exercises
        git:
          url: https://github.com/spring-academy/course-spring-brasb-build-a-rest-api-code
          ref: main
        newRootPath: .
  request:
    parameters:
    - name: USER_DOMAIN
      value: "unknown.domain"
    - name: USER_EMAIL
      value: "somebody@unknown.domain"
  session:
    env:
      - name: LESSON_LABEL
        value: first-rest-endpoint-start
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: default
      editor:
        enabled: true
    dashboards:
      - name: Editor
      - name: Terminal
